# Data mining Assignment
## Ashish Singh
### 20310007

## Importing Libraries and Dataset

In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.svm import SVC

In [2]:
rawdata = pd.read_csv("advertising.csv")
rawdata.shape

(1000, 10)

In [3]:
rawdata.head(10)

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Ad Topic Line,City,Male,Country,Timestamp,Clicked on Ad
0,68.95,35,61833.90,256.09,Cloned 5thgeneration orchestration,Wrightburgh,0,Tunisia,27-03-2016 00:53,0
1,80.23,31,68441.85,193.77,Monitored national standardization,West Jodi,1,Nauru,04-04-2016 01:39,0
2,69.47,26,59785.94,236.50,Organic bottom-line service-desk,Davidton,0,San Marino,13-03-2016 20:35,0
3,74.15,29,54806.18,245.89,Triple-buffered reciprocal time-frame,West Terrifurt,1,Italy,10-01-2016 02:31,0
4,68.37,35,73889.99,225.58,Robust logistical utilization,South Manuel,0,Iceland,03-06-2016 03:36,0
5,59.99,23,59761.56,226.74,Sharable client-driven software,Jamieberg,1,Norway,19-05-2016 14:30,0
6,88.91,33,53852.85,208.36,Enhanced dedicated support,Brandonstad,0,Myanmar,28-01-2016 20:59,0
7,66.00,48,24593.33,131.76,Reactive local challenge,Port Jefferybury,1,Australia,07-03-2016 01:40,1
8,74.53,30,68862.00,221.51,Configurable coherent function,West Colin,1,Grenada,18-04-2016 09:33,0
9,69.88,20,55642.32,183.82,Mandatory homogeneous architecture,Ramirezton,1,Ghana,11-07-2016 01:42,0

In [4]:
del_columns = ["Ad Topic Line","City","Country","Timestamp"]
rawdata.drop(columns = del_columns, inplace = True)
x = rawdata.drop(columns = "Clicked on Ad")
x.head(10)

   Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  Male
0                     68.95   35     61833.90                256.09     0
1                     80.23   31     68441.85                193.77     1
2                     69.47   26     59785.94                236.50     0
3                     74.15   29     54806.18                245.89     1
4                     68.37   35     73889.99                225.58     0
5                     59.99   23     59761.56                226.74     1
6                     88.91   33     53852.85                208.36     0
7                     66.00   48     24593.33                131.76     1
8                     74.53   30     68862.00                221.51     1
9                     69.88   20     55642.32                183.82     1

In [5]:
# x=(x-x.mean())/x.std()

In [6]:
# x.head(10)

In [7]:
y = rawdata["Clicked on Ad"].copy()
y.head(10)

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    1
8    0
9    0
Name: Clicked on Ad, dtype: int64

In [8]:
c=[0.01,0.1,1,10,100,1000] # different values of c parameter

## SVM Models
### 1) Linear Kernel

In [9]:
for i in c:
    model = SVC(kernel = 'linear' ,C = i)
    model.fit(x,y)
    pred = model.predict(x)
    SupportVector = model.support_vectors_
    accuracy = model.score(x, y)
    print(f"Value of C: {i}")
    print(f"Confusion matrix: \n{confusion_matrix(pred,y)}")
    print(f"Number of Support Vector: {SupportVector.size}")
    print(f"Accuracy of the model: {accuracy}\n\n")

Value of C: 0.01
Confusion matrix:
[[494  21]
 [  6 479]]
Number of Support Vector: 365
Accuracy of the model: 0.973


Value of C: 0.1
Confusion matrix:
[[494  22]
 [  6 478]]
Number of Support Vector: 345
Accuracy of the model: 0.972


Value of C: 1
Confusion matrix:
[[489  21]
 [ 11 479]]
Number of Support Vector: 340
Accuracy of the model: 0.968


Value of C: 10
Confusion matrix:
[[492  21]
 [  8 479]]
Number of Support Vector: 330
Accuracy of the model: 0.971


Value of C: 100
Confusion matrix:
[[492  19]
 [  8 481]]
Number of Support Vector: 340
Accuracy of the model: 0.973


Value of C: 1000
Confusion matrix:
[[489  22]
 [ 11 478]]
Number of Support Vector: 325
Accuracy of the model: 0.967

### 2) Polynomial Kernel

In [10]:
for i in c:
    model = SVC(kernel = 'poly',degree = 2,C = i)
    model.fit(x,y)
    pred = model.predict(x)
    SupportVector = model.support_vectors_
    accuracy = model.score(x, y)
    print(f"Value of C: {i}")
    print(f"Confusion matrix: \n{confusion_matrix(pred,y)}")
    print(f"Number of Support Vector: {SupportVector.size}")
    print(f"Accuracy of the model: {accuracy}\n\n")

Value of C: 0.01
Confusion matrix:
[[388 173]
 [112 327]]
Number of Support Vector: 4360
Accuracy of the model: 0.715


Value of C: 0.1
Confusion matrix:
[[379 168]
 [121 332]]
Number of Support Vector: 3540
Accuracy of the model: 0.711


Value of C: 1
Confusion matrix:
[[375 167]
 [125 333]]
Number of Support Vector: 3380
Accuracy of the model: 0.708


Value of C: 10
Confusion matrix:
[[374 166]
 [126 334]]
Number of Support Vector: 3360
Accuracy of the model: 0.708


Value of C: 100
Confusion matrix:
[[395 148]
 [105 352]]
Number of Support Vector: 3355
Accuracy of the model: 0.747


Value of C: 1000
Confusion matrix:
[[469  56]
 [ 31 444]]
Number of Support Vector: 2890
Accuracy of the model: 0.913

### 3) RBF Kernel

In [11]:
for i in c:
    model = SVC(kernel = 'rbf',C = i)
    model.fit(x,y)
    pred = model.predict(x)
    SupportVector = model.support_vectors_
    accuracy = model.score(x, y)
    print(f"Value of C: {i}")
    print(f"Confusion matrix: \n{confusion_matrix(pred,y)}")
    print(f"Number of Support Vector: {SupportVector.size}")
    print(f"Accuracy of the model: {accuracy}\n\n")

Value of C: 0.01
Confusion matrix:
[[449 246]
 [ 51 254]]
Number of Support Vector: 5000
Accuracy of the model: 0.703


Value of C: 0.1
Confusion matrix:
[[410 197]
 [ 90 303]]
Number of Support Vector: 3700
Accuracy of the model: 0.713


Value of C: 1
Confusion matrix:
[[428 213]
 [ 72 287]]
Number of Support Vector: 3290
Accuracy of the model: 0.715


Value of C: 10
Confusion matrix:
[[423 206]
 [ 77 294]]
Number of Support Vector: 3180
Accuracy of the model: 0.717


Value of C: 100
Confusion matrix:
[[431 195]
 [ 69 305]]
Number of Support Vector: 3150
Accuracy of the model: 0.736


Value of C: 1000
Confusion matrix:
[[465  95]
 [ 35 405]]
Number of Support Vector: 2940
Accuracy of the model: 0.87

In [ ]:
# After Normalizing the data, we can get better accuracy